//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.1
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfUpdaterHelper.WcfUpdaterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfUpdaterService.IUpdateWcfService")]
    public interface IUpdateWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpdateWcfService/DoUpdate", ReplyAction="http://tempuri.org/IUpdateWcfService/DoUpdateResponse")]
        string DoUpdate(string infoXmlPath);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUpdateWcfServiceChannel : WcfUpdaterHelper.WcfUpdaterService.IUpdateWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateWcfServiceClient : System.ServiceModel.ClientBase<WcfUpdaterHelper.WcfUpdaterService.IUpdateWcfService>, WcfUpdaterHelper.WcfUpdaterService.IUpdateWcfService {
        
        public UpdateWcfServiceClient() {
        }
        
        public UpdateWcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UpdateWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdateWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdateWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DoUpdate(string infoXmlPath) {
            return base.Channel.DoUpdate(infoXmlPath);
        }
    }
}
